### ISSUE TITLE
Eset NOD32 Say updater file is a virus but im sure it a false positive ??

### ISSUE THREAD

**Issue by Felzow47** [clowd/Clowd#27]

**Comment by caesay** [comment]
Clowd is currently not codesigned (because code signing certificates are expensive), so it's more likely to be picked up by virus scanners. 

You're welcome to review the code and compile Clowd yourself if you are worried about viruses. If you're not worried, you can simply tell your AV that Clowd is not a virus.

**Comment by Felzow47** [comment]
ok thx i will do this
